### ISSUE TITLE
Package is not necessarily user-friendly

### ISSUE THREAD

**Issue by cthoyt** [Thakar-Lab/WikiNetworks#18]
There are a couple places where this package claims to be user-friendly. I've written a lot of packages that I was proud of, and also fallen into the trap of claiming this, but it wasn't how other people felt. Here are a few things that I can immediately note that make this package not user-friendly that you can improve:

1. No installation notes on readme
2. No link to open-access publication / preprint on readme
3. No reference documentation for functions in the package (tutorials in notebooks are nice, but it's not the same.
4. No simple code examples on front page
5. Non-standard repository layout (why is the package hiding inside a folder?)
6. No consistent code style enforcement (I'd suggest you check out [black](https://github.com/psf/black) and flake8)
7. Use badges from sites like https://shields.io/ to more concisely show information about which versions are supported, based on your setup.cfg/pyproject.toml
8. Use pyroma to check that there's enough metadata that people an understand something about your package (it's missing most things right now)
9. Write some unit tests, how can anyone trust that the code will continue to work without them?

**Comment by cthoyt** [comment]
Not sure if closing an issue without comment is good form either :/

**Comment by mgp13** [comment]
>

**Comment by mgp13** [comment]
I actually quite agree :/ Thank you for your detailed review. I believe we’ve addressed most of your comments, although I agree that points 8 and 9 will need some more time and work. 
I do appreciate the care with which your comment was made. However since you had no questions I believed (clearly incorrectly) that you did not need a response other than a material one, ie me following your suggestions. I hope this response is satisfactory.

**Comment by cthoyt** [comment]
Typically it helps people who write issues on GitHub if you tag the issue number in related commit messages (see [here](https://stackoverflow.com/questions/1687262/link-to-the-issue-number-on-github-within-a-commit-message) for an explanation on how to do this). Maybe you could go find the relevant commits and post them here, or at least explain how you went about solving some of these issues

**Comment by mgp13** [comment]
I want to acknowledge that I have seen this comment and once again appreciate your time :/ It’s certainly good form to credit those who open issues, although since this doesn’t directly impact usability I will address it a little later and hope that this is acceptable. Thanks :/
