### ISSUE TITLE
listPathways(organism = 'Homo sapiens') returns all species

### ISSUE THREAD

**Issue by DWgit** [Thakar-Lab/WikiNetworks#24]
The code below retrieves all pathways, not just HS
```
from wikinetworks import *

s = WikiPathways()
hs_pathways = s.listPathways(organism = 'Homo sapiens')
print(hs_pathways.species.value_counts())
```
output:

```
Homo sapiens                  1417
Bos taurus                     273
Mus musculus                   236
Rattus norvegicus              174
``` 
(snip)

The issue occurs with WikiNetworks Version: 1.1.2, running on conda Python 3.9.12

**Comment by mgp13** [comment]
This is an error in the bioservices package, which is an upstream dependency. Bioservices loads the WikiPathways database (s=WikiPathways()) and provides the associated function 'listPathways'. The 'organism' parameter for listPathways unfortunately there doesn't look like much we can do about this except submitting a bug report to bioservices. Luckily you don't really need this particular function to run wikinetworks; it's easy enough to select the pathways that you need from the dataframe returned by listPathways.

--
Mukta
